window.CastData = {

  contestants: {
    // ── S1 Borneo ──────────────────────────────────────────────────────
    "richard-hatch":      { name: "Richard Hatch",                   bio: "The fabulous gay star of season 1 is revealed in season 8 to be a weirdo. Deeply disappointing. I hope not to be seeing him again." },
    "kelly-wiglesworth":  { name: "Kelly Wiglesworth",               bio: "" },
    "rudy-boesch":        { name: "Rudy Boesch",                     bio: "" },
    "susan-hawk":         { name: "Susan Hawk",                      bio: "The icon responsible for the game-shaping 'snakes and rats' speech." },
    "sean-kenniff":       { name: "Sean Kenniff",                    bio: "Voted alphabetically post-merge." },
    "colleen-haskell":    { name: "Colleen Haskell",                 bio: "" },
    "gervase-peterson":   { name: "Gervase Peterson",                bio: "" },
    "jenna-lewis":        { name: "Jenna Lewis",                     bio: "" },
    "greg-buis":          { name: "Greg Buis",                       bio: "" },
    "gretchen-cordy":     { name: "Gretchen Cordy",                  bio: "" },
    "joel-klug":          { name: "Joel Klug",                       bio: "" },
    "dirk-been":          { name: "Dirk Been",                       bio: "Brought a bible!" },
    "ramona-gray":        { name: "Ramona Gray",                     bio: "" },
    "stacey-stillman":    { name: "Stacey Stillman",                 bio: "" },
    "b-b-andersen":       { name: "B.B. Andersen",                   bio: "Fervently worked on building a shelter and then seemingly threw in the towel immediately!" },
    "sonja-christopher":  { name: "Sonja Christopher",               bio: "The first every person to be voted out of Survivor. Poor Sonja." },

    // ── S2 The Australian Outback ───────────────────────────────────────
    "tina-wesson":        { name: "Tina Wesson",                     bio: "" },
    "colby-donaldson":    { name: "Colby Donaldson",                 bio: "" },
    "amber-brkich":       { name: "Amber Brkich",                    bio: "Completely anonymous in the edit of Australian Outback, but somehow is brought back for All-Stars and ekes out a win based on her relationship with a certain Boston Rob." },
    "jerri-manthey":      { name: "Jerri Manthey",                   bio: "The first 'villain'. Love her. And I love how she's just as annoying on her second go!" },
    "elisabeth-filarski": { name: "Elisabeth Filarski",              bio: "" },
    "rodger-bingham":     { name: "Rodger Bingham",                  bio: "" },
    "alicia-calaway":     { name: "Alicia Calaway",                  bio: "" },
    "keith-famie":        { name: "Keith Famie",                     bio: "" },
    "nick-brown":         { name: "Nick Brown",                      bio: "" },
    "jeff-varner":        { name: "Jeff Varner",                     bio: "" },
    "michael-skupin":     { name: "Michael Skupin",                  bio: "" },
    "kimmi-kappenberg":   { name: "Kimmi Kappenberg",                bio: "Most Australian Outback drama in Kucha stemmed from the fact that she is a vegetarian. Woke messy queen!" },
    "mitchell-olson":     { name: "Mitchell Olson",                  bio: "" },
    "maralyn-hershey":    { name: "Maralyn Hershey",                 bio: "AKA Mad Dog!" },
    "kel-gleason":        { name: "Kel Gleason",                     bio: "Accused of smuggling beef jerky into the show and keeping it for himself. That was... not true, right?" },
    "debb-eaton":         { name: "Debb Eaton",                      bio: "" },

    // ── S3 Africa ──────────────────────────────────────────────────────
    "ethan-zohn":         { name: "Ethan Zohn",                      bio: "" },
    "kim-johnson":        { name: "Kim Johnson",                     bio: "" },
    "lex-van-den-berghe": { name: "Lex van den Berghe",              bio: "A slightly odd, neurotic character. But honestly he sort of won me over in All-Stars - one of the few who comes across better in that season." },
    "tom-buchanan":       { name: "Tom Buchanan",                    bio: "Seemingly homophobic. And very weird to the women of season 3. I don't get the appeal at all." },
    "teresa-cooper":      { name: "Teresa Cooper",                   bio: "AKA T-Bird! Cast the 'mystery vote' against Lex which helped spice up the mid-season." },
    "frank-garrison":     { name: "Frank Garrison",                  bio: "Seemingly homophobic." },
    "brandon-quinton":    { name: "Brandon Quinton",                 bio: "Chaotic demon twink. Obsessed." },
    "kim-powers":         { name: "Kim Powers",                      bio: "" },
    "kelly-goldsmith":    { name: "Kelly Goldsmith",                 bio: "" },
    "linda-spencer":      { name: "Linda Spencer",                   bio: "The way she mocks Lindsey is the highlight of the season for me." },
    "clarence-black":     { name: "Clarence Black",                  bio: "" },
    "lindsey-richter":     { name: "Lindsey Richter",                  bio: "" },
    "silas-gaither":      { name: "Silas Gaither",                   bio: "" },
    "carl-schmidt":       { name: "Carl Schmidt",                    bio: "" },
    "jessie-camacho":     { name: "Jessie Camacho",                  bio: "" },
    "diane-ogden":        { name: "Diane Ogden",                     bio: "" },

    // ── S4 Marquesas ──────────────────────────────────────────────────
    "vecepia-towery":       { name: "Vecepia Towery",                bio: "" },
    "neleh-dennis":         { name: "Neleh Dennis",                  bio: "Mormon." },
    "paschal-english":      { name: "Paschal English",               bio: "" },
    "kathy-vavrick-obrien": { name: "Kathy Vavrick-O'Brien",        bio: "One of the earliest and smartest strategic players, despite potentially being overshadowed on each of her own seasons by Boston Rob." },
    "sean-rector":          { name: "Sean Rector",                   bio: "" },
    "rob-mariano":          { name: "Rob Mariano",                   bio: "AKA Boston Rob." },
    "tammy-leitner":        { name: "Tammy Leitner",                 bio: "" },
    "the-general":          { name: "Robert DeCanio", bio: "AKA The General." },
    "zoe-zanidakis":        { name: "Zoe Zanidakis",                 bio: "" },
    "john-carroll":         { name: "John Carroll",                  bio: "Regina George figure of the first cracked alliance." },
    "gabriel-cade":         { name: "Gabriel Cade",                  bio: "" },
    "gina-crews":           { name: "Gina Crews",                    bio: "" },
    "sarah-jones":          { name: "Sarah Jones",                   bio: "" },
    "hunter-ellis":         { name: "Hunter Ellis",                  bio: "" },
    "patricia-jackson":     { name: "Patricia Jackson",              bio: "" },
    "peter-harkey":         { name: "Peter Harkey",                  bio: "" },

    // ── S5 Thailand ───────────────────────────────────────────────────
    "brian-heidik":       { name: "Brian Heidik",                    bio: "" },
    "clay-jordan":        { name: "Clay Jordan",                     bio: "" },
    "jan-gentry":         { name: "Jan Gentry",                      bio: "" },
    "helen-glover":       { name: "Helen Glover",                    bio: "" },
    "ted-rogers":         { name: "Ted Rogers",                      bio: "" },
    "ken-stafford":       { name: "Ken Stafford",                    bio: "" },
    "jake-billingsley":   { name: "Jake Billingsley",                bio: "" },
    "penny-ramsey":       { name: "Penny Ramsey",                    bio: "" },
    "shii-ann-huang":     { name: "Shii Ann Huang",                  bio: "" },
    "robb-zbacnik":       { name: "Robb Zbacnik",                    bio: "" },
    "stephanie-dill":     { name: "Stephanie Dill",                  bio: "" },
    "ghandia-johnson":    { name: "Ghandia Johnson",                 bio: "" },
    "jed-hildebrand":     { name: "Jed Hildebrand",                  bio: "" },
    "john-raymond":       { name: "John Raymond",                    bio: "" },
    "tanya-vance":        { name: "Tanya Vance",                     bio: "" },
    "erin-collins":        { name: "Erin Collins",                     bio: "" },

    // ── S6 The Amazon ─────────────────────────────────────────────────
    "jenna-morasca":        { name: "Jenna Morasca",                 bio: "" },
    "matthew-von-ertfelda": { name: "Matthew von Ertfelda",         bio: "" },
    "rob-cesternino":       { name: "Rob Cesternino",                bio: "" },
    "butch-lockley":        { name: "Butch Lockley",                 bio: "" },
    "heidi-strobel":        { name: "Heidi Strobel",                 bio: "" },
    "christy-smith":        { name: "Christy Smith",                 bio: "" },
    "alex-bell":            { name: "Alex Bell",                     bio: "" },
    "deena-bennett":        { name: "Deena Bennett",                 bio: "" },
    "shawna-mitchell":      { name: "Shawna Mitchell",               bio: "" },
    "dave-johnson":         { name: "Dave Johnson",                  bio: "" },
    "roger-sexton":         { name: "Roger Sexton",                  bio: "" },
    "joanna-ward":          { name: "Joanna Ward",                   bio: "" },
    "jeanne-hebert":        { name: "Jeanne Hebert",                 bio: "" },
    "janet-koth":           { name: "Janet Koth",                    bio: "" },
    "daniel-lue":           { name: "Daniel Lue",                    bio: "" },
    "ryan-aiken":           { name: "Ryan Aiken",                    bio: "" },

    

    // ── S7 Pearl Islands ──────────────────────────────────────────────
    "sandra-diaz-twine":  { name: "Sandra Diaz-Twine",               bio: "Although she does stumble into victory, Sandra is extremely likeable. I was won over when she discussed her plan to hide all of the survival equipment when she felt her time was near! The Pearl Islands episode 1 gimmick is thoroughly ruined by the fact she is an hispanohablante (which leads to great suffering for the Morgan tribe) but it's nice to see some latino representation!" },
    "lillian-morris":     { name: "Lillian Morris",                  bio: "I did enjoy her and her friendship with Skinny Ryan, though the whole conscientious scout leader bit did get quite old." },
    "jon-dalton":         { name: "Jonny Fairplay",                      bio: "AKA Johnny Fairplay! I love him. A pure unfettered villain - but never comes across as mean-spirited." },
    "darrah-johnson":     { name: "Darrah Johnson",                  bio: "" },
    "burton-roberts":     { name: "Burton Roberts",                  bio: "This man is so good-looking... wow. I enjoyed his bromance with Johnny Fairplay and his special relationship with Lillian. Ultimately, it was also satisfying seeing him receive his comeuppance for underestimating the girls and taking Lillian for granted." },
    "christa-hastie":     { name: "Christa Hastie",                  bio: "" },
    "rupert-boneham":     { name: "Rupert Boneham",                  bio: "A real character! Seemingly, he loves and excels at fishing with a spear. The way he lost his temper at Johnny Fairplay was shocking and uncomfortable and somewhat soured me on him and his whole nice guy shtick. He isn't much of a strategist either, which is fine in Pearl Islands but really contributes in dragging down All-Stars." },
    "tijuana-bradley":    { name: "Tijuana Bradley",                 bio: "" },
    "andrew-savage":      { name: "Andrew Savage",                   bio: "The first person (that I noticed) to get referred to by their surname by Jeff Probst during challenges." },
    "osten-taylor":       { name: "Osten Taylor",                    bio: "The first (explicit) quitter." },
    "trish-dunn":         { name: "Trish Dunn",                      bio: "" },
    "shawn-cohen":        { name: "Shawn Cohen",                     bio: "Part of the mean girl Drake clique." },
    "michelle-tesauro":   { name: "Michelle Tesauro",                bio: "Part of the mean girl Drake clique." },
    "ryan-opray":         { name: "Ryan Opray",                      bio: "" },
    "nicole-delma":       { name: "Nicole Delma",                    bio: "Fabulous dress." },
    "ryan-shoulders":     { name: "Ryan Shoulders",                  bio: "AKA Skinny Ryan. I immediately thought he might win; I'm not sure why. I really liked his energy." },

    // ── S9 Vanuatu ─────────────────────────────────────────────────

    "brook-geraghty":     { name: "Brook Geraghty",                  bio: "" },
    "dolly-neely":     { name: "Dolly Neely",                  bio: "She tried to play with both the olds and the youngs and ended up getting voted out for it." },
    "john-palyok":     { name: "John Palyok",                  bio: "AKA JP." },
    "mia-galeotalanza":     { name: "Mia Galeotalanza",                  bio: "She was part of an iconic shouting match with Twila." },
    "brady-finta":     { name: "Brady Finta",                  bio: "He climbed the pole in the first episode to get the rock down." },
    "travis-simpson":     { name: "Travis Simpson",                  bio: "AKA Bubba." },
    "lisa-keiffer":    { name: "Lisa Keiffer",                 bio: "No shade, but why was this woman part of the young-people alliance."},
    "john-kenney":     { name: "John Kenney",                  bio: "" },
    "rory-freeman":     { name: "Rory Freeman",                  bio: "" },
    "lea-masters":     { name: "Lea Masters",                  bio: "AKA Sarge." },
    "chad-crittenden":     { name: "Chad Crittenden",                  bio: "He uses a prosthetic leg." },
    "leann-slaby":     { name: "Leann Slaby",                  bio: "" },
    "ami-cusack":     { name: "Ami Cusack",                  bio: "She struck me as very smart, but perhaps not smart enough to lay low a little more than she did." },
    "julie-berry":     { name: "Julie Berry",                  bio: "" },
    "eliza-orlins":     { name: "Eliza Orlins",                  bio: "She is easily my favourite character from Vanuatu. From her episode 2 gambit where she manages to co-ordinate a blindside on Dolly to her expression as she walks out of tribal council is just one iconic line and facial expression after another." },
    "scout-cloud-lee": {name: "Scout Cloud Lee",               bio: "Adorable lesbian granny. She was sweet."},
    "twila-tanner":     { name: "Twila Tanner",                  bio: "She comes across as a deeply unlikeable diva... but I kind of love her for that. Her open hatred for the younger women, especially Eliza, fuels most of Vanuatu." },
    "chris-daughtery":     { name: "Chris Daughtery",                  bio: "He played very hard, and succeeded in disrupting an all-women alliance when there were six left. There were perhaps a few unnecessary lies and emotional manipulations happening - but his strategy worked flawlessly (bringing the deeply unlikeable Twila into the final two). His performance at final tribal council was remarkably convincing." },


    // ── S10 Palau ──────────────────────────────────────────────────────
    "tom-westman":      { name: "Tom Westman",      bio: "Probably just the edit, but he's pretty much a real-life super-hero. Ferociously strong in challenges, kind to everyone, a game player and leader but not a liar... all quite unique qualitites amongst winners." },
    "katie-gallagher":  { name: "Katie Gallagher",  bio: "Despite the best efforts of the edit, I do think she was a little bit of a mean girl." },
    "ian-rosenberger":  { name: "Ian Rosenberger",  bio: "He's so tall and thin... I thought he would blow away! His decision after twelve hours (!!) to step down from the immunity challenge is kind of baffling, but he was smart and caused much of the drama, despite being genuinely well-intentioned and kind-heartened." },
    "jenn-lyon":        { name: "Jenn Lyon",         bio: "She was nowhere to be found in the edit for much of the season. Which is a shame, because from what we saw of her she seemed smart and funny." },
    "caryn-groedel":    { name: "Caryn Groedel",    bio: "An icon! Her posture is so terrible! Her crash-outs were some of the highlights of the season. I feel a bit bad for her though - there was definitely a cliquey undercurrent to this season, and Tom sort of lead her on the most. I resent that she ratted out the women's alliance earlier on in the game, though I don't think that was actually going anywhere to be fair." },
    "gregg-carey":      { name: "Gregg Carey",       bio: "" },
    "stephenie-lagrossa": { name: "Stephenie LaGrossa", bio: "Poor Stephenie! The first (and perhaps only...?) tribe of one! It's a real shame she wasn't able to stir much up at Koror - but her eventual elimination is proof that starting tribes must actually try to win immunity challenges." },
    "coby-archa":       { name: "Coby Archa",        bio: "Another chaotic gay guy! I love this developing Survivor trope. I would have loved to see more from him, but he fell victim to not being one of the clique 5. Disappointing." },
    "janu-tornell":     { name: "Janu Tornell",      bio: "Okay so she genuinely did seem like an odd woman. But I loved her chaotic, frantic energy - and how she finds release by being separated from her bullies." },
    "bobby-jon-drinkard": { name: "Bobby Jon Drinkard", bio: "" },
    "james-miller":     { name: "James Miller",      bio: "" },
    "ibrehem-rahman":   { name: "Ibrehem Rahman",    bio: "He was muslim. I wonder if they told him which direction Mecca was in." },
    "willard-smith":    { name: "Willard Smith",     bio: "" },
    "angie-jakusz":     { name: "Angie Jakusz",      bio: "Alt girl who turned out to be strong. She had some kind of story set up with Coby in episode one and then that didn't go anywhere... weird." },
    "jeff-wilson":      { name: "Jeff Wilson",       bio: "He twisted his ankle and requests to be voted off. Jeff (Probst) gave him grief for it at the reunion, but it seemed necessary. All the challenges involve running around and swimming and climbing... surely you know this Jeff." },
    "kim-mullen":       { name: "Kim Mullen",        bio: "She had a fling with Jeff" },
    "ashlee-ashby":     { name: "Ashlee Ashby",      bio: "Voted out for being lazy." },
    "jolanda-jones":    { name: "Jolanda Jones",     bio: "" },
    "wanda-shirk":      { name: "Wanda Shirk",       bio: "She was eliminated before the game even started. A cruel twist!" },
    "jonathan-libby":   { name: "Jonathan Libby",   bio: "He was eliminated before the game even started, punished for (alongside Stephenie) being one of the first to jump off the boat. A cruel twist!" },

    // ── S11 Guatemala ──────────────────────────────────────────────────
    "danni-boatwright":  { name: "Danni Boatwright",  bio: "It's kind of possible to write her off as a little bit of a fluke winner like Jenna Morasca, but on reflection she actually did a lot of posturing to make it from the post-swap Yaxha minority to the end." },
    "rafe-judkins":      { name: "Rafe Judkins",       bio: "" },
    "lydia-morales":     { name: "Lydia Morales",      bio: "" },
    "cindy-hall":        { name: "Cindy Hall",          bio: "" },
    "gary-hogeboom":     { name: "Gary Hogeboom",      bio: "He lied about his job, or former job, as an NFL quarterback." },
    "judd-sergeant":     { name: "Judd Sergeant",      bio: "I guess he could be described as a villain on Guatemala. His ADD crash-out towards Margaret has to be a season highlight!" },
    "jamie-newton":      { name: "Jamie Newton",       bio: "He kind of went insane... but I love that. His BDP sort of spiral into paranoia and insecurity was great to watch." },
    "brandon-bellinger": { name: "Brandon Bellinger",  bio: "" },
    "amy-ohara":         { name: "Amy O'Hara",         bio: "" },
    "brian-corridan":    { name: "Brian Corridan",     bio: "He looks so much like Ollie Bearman! This is one of the most surprising and disappointing pre-merge losses so far. I really thought he was going quite far, and I liked him a lot!" },
    "margaret-bobonich": { name: "Margaret Bobonich",  bio: "" },
    "blake-towsley":     { name: "Blake Towsley",      bio: "Hillariously annoying. The other people called him 'Golden Boy' because of it!" },
    "morgan-mcdevitt":   { name: "Morgan McDevitt",    bio: "" },
    "brooke-struck":     { name: "Brooke Struck",      bio: "" },
    "brianna-varela":    { name: "Brianna Varela",     bio: "" },
    "jim-lynch":         { name: "Jim Lynch",           bio: "" },

    // ── S12 Panama ─────────────────────────────────────────────────────
    "aras-baskauskas":    { name: "Aras Baskauskas",    bio: "He was somewhat of a sleeper winner in the edit - but by the end I was thoroughly impressed with him. Especially his loyalty to Cirie and his absolute abhorrence of Terry!" },
    "danielle-dilorenzo": { name: "Danielle DiLorenzo", bio: "" },
    "terry-deitz":        { name: "Terry Deitz",         bio: "He was a bit of a challenge superhero on his season, but despite being a resilient underdog did not really come off well. I wasn't rooting for him at any point. His selfishness with the idol condemned us to a more boring version of what could have been a ten/ten season." },
    "shane-powers":       { name: "Shane Powers",        bio: "He counts as the villain of the season I suppose. And so, of course, I adore him and his neurotic, nicotine-withdrawl-fuelled ways." },
    "cirie-fields":       { name: "Cirie Fields",         bio: "She is easily my favourite Survivor contestant of all time." },
    "courtney-marit":     { name: "Courtney Marit",      bio: "" },
    "bruce-kanegai":      { name: "Bruce Kanegai",       bio: "" },
    "sally-schumann":     { name: "Sally Schumann",      bio: "" },
    "austin-carty":       { name: "Austin Carty",        bio: "" },
    "nick-stanbury":      { name: "Nick Stanbury",       bio: "" },
    "dan-barry":          { name: "Dan Barry",            bio: "" },
    "ruth-marie-milliman":{ name: "Ruth Marie Milliman", bio: "" },
    "bobby-mason":        { name: "Bobby Mason",          bio: "" },
    "melinda-hyder":      { name: "Melinda Hyder",       bio: "" },
    "misty-giles":        { name: "Misty Giles",          bio: "" },
    "tina-scheer":        { name: "Tina Scheer",          bio: "" },
    
    // ── S13 Cook Islands ───────────────────────────────────────────────
    "yul-kwon":           { name: "Yul Kwon",             bio: "" },
    "ozzy-lusth":         { name: "Ozzy Lusth",           bio: "" },
    "becky-lee":          { name: "Becky Lee",             bio: "" },
    "sundra-oakley":      { name: "Sundra Oakley",        bio: "" },
    "parvati-shallow":    { name: "Parvati Shallow",      bio: "" },
    "candice-woodcock":   { name: "Candice Woodcock",     bio: "" },
    "adam-gentry":        { name: "Adam Gentry",          bio: "" },
    "jonathan-penner":    { name: "Jonathan Penner",      bio: "" },
    "nate-gonzalez":      { name: "Nate Gonzalez",        bio: "" },
    "jenny-guzon-bae":    { name: "Jenny Guzon-Bae",      bio: "" },
    "cristina-coria":     { name: "Cristina Coria",       bio: "" },
    "cao-boi-bui":        { name: "Cao Boi Bui",           bio: "" },
    "flicka-smith":       { name: "Flicka Smith",          bio: "" },
    "brad-virata":        { name: "Brad Virata",           bio: "" },
    "rebecca-borman":     { name: "Rebecca Borman",       bio: "" },
    "cecilia-mansilla":   { name: "Cecilia Mansilla",     bio: "" },
    "stephannie-favor":   { name: "Stephannie Favor",     bio: "" },
    "jp-calderon":        { name: "J.P. Calderon",         bio: "" },
    "billy-garcia":       { name: "Billy Garcia",          bio: "" },
    "sekou-bunch":        { name: "Sekou Bunch",           bio: "" },


        // ── S14 Fiji ───────────────────────────────────────────────────────
    "earl-cole":          { name: "Earl Cole",            bio: "" },
    "cassandra-franklin": { name: "Cassandra Franklin",   bio: "" },
    "dreamz-herd":        { name: "Dreamz Herd",          bio: "" },
    "yau-man-chan":       { name: "Yau-Man Chan",         bio: "" },
    "boo-bernis":         { name: "Boo Bernis",           bio: "" },
    "stacy-kimball":      { name: "Stacy Kimball",        bio: "" },
    "alex-angarita":      { name: "Alex Angarita",        bio: "" },
    "mookie-lee":         { name: "Mookie Lee",           bio: "" },
    "edgardo-rivera":     { name: "Edgardo Rivera",       bio: "" },
    "michelle-yi":        { name: "Michelle Yi",          bio: "" },
    "lisi-linares":       { name: "Lisi Linares",         bio: "" },
    "rocky-reid":         { name: "Rocky Reid",           bio: "" },
    "anthony-robinson":   { name: "Anthony Robinson",     bio: "" },
    "rita-verreos":       { name: "Rita Verreos",         bio: "" },
    "liliana-gomez":      { name: "Liliana Gomez",        bio: "" },
    "gary-stritesky":     { name: "Gary Stritesky",       bio: "" },
    "sylvia-kwan":        { name: "Sylvia Kwan",          bio: "" },
    "erica-durousseau":   { name: "Erica Durousseau",     bio: "" },
    "jessica-deben":      { name: "Jessica deBen",        bio: "" },


        // ── S15 China ──────────────────────────────────────────────────────
    "todd-herzog":        { name: "Todd Herzog",        bio: "" },
    "courtney-yates":     { name: "Courtney Yates",     bio: "" },
    "amanda-kimmel":      { name: "Amanda Kimmel",      bio: "" },
    "denise-martin":      { name: "Denise Martin",      bio: "" },
    "peih-gee-law":       { name: "Peih-Gee Law",       bio: "" },
    "erik-huffman":       { name: "Erik Huffman",       bio: "" },
    "jaime-dugan":        { name: "Jaime Dugan",        bio: "" },
    "jean-robert-bellande": { name: "Jean-Robert Bellande", bio: "" },
    "james-clement":      { name: "James Clement",      bio: "" },
    "aaron-reisberger":   { name: "Aaron Reisberger",   bio: "" },
    "leslie-nease":       { name: "Leslie Nease",       bio: "" },
    "dave-cruser":        { name: "Dave Cruser",        bio: "" },
    "ashley-massaro":     { name: "Ashley Massaro",     bio: "" },
    "sherea-lloyd":       { name: "Sherea Lloyd",       bio: "" },
    "frosti-zernow": { name: "Frosti Zernow", bio: "" },
    "chicken-morris":       { name: "Chicken Morris",       bio: "" },


    // ── S16 Micronesia (Fans) ──────────────────────────────────────────────────────

    "erik-reichenbach":    { name: "Erik Reichenbach",     bio: "" },
    "natalie-bolton":      { name: "Natalie Bolton",       bio: "" },
    "alexis-jones":        { name: "Alexis Jones",         bio: "" },
    "jason-siska":         { name: "Jason Siska",          bio: "" },
    "tracy-hughes-wolf":   { name: "Tracy Hughes-Wolf",    bio: "" },
    "chet-welch":          { name: "Chet Welch",           bio: "" },
    "kathy-sleckman":      { name: "Kathy Sleckman",       bio: "" },
    "mikey-bortone":       { name: "Mikey Bortone",        bio: "" },
    "mary-sartain":        { name: "Mary Sartain",         bio: "" },
    "joel-anderson":       { name: "Joel Anderson",        bio: "" },
    
      },

  seasons: [
    {
      number: 1, name: "Borneo", year: 2000, color: "#c8845a", allstar: false,
      favourites: ["richard-hatch", "susan-hawk", "greg-buis"],
      cast: [
        { id: "richard-hatch",     placement: 1,  jury: false, starting_tribe: "tagi" },
        { id: "kelly-wiglesworth", placement: 2,  jury: false, starting_tribe: "tagi" },
        { id: "rudy-boesch",       placement: 3,  jury: true, starting_tribe: "tagi"  },
        { id: "susan-hawk",        placement: 4,  jury: true, starting_tribe: "tagi"  },
        { id: "sean-kenniff",      placement: 5,  jury: true, starting_tribe: "tagi"  },
        { id: "colleen-haskell",   placement: 6,  jury: true, starting_tribe: "pagong"  },
        { id: "gervase-peterson",  placement: 7,  jury: true, starting_tribe: "pagong"  },
        { id: "jenna-lewis",       placement: 8,  jury: true, starting_tribe: "pagong" },
        { id: "greg-buis",         placement: 9,  jury: true, starting_tribe: "pagong" },
        { id: "gretchen-cordy",    placement: 10, jury: false, starting_tribe: "pagong" },
        { id: "joel-klug",         placement: 11, jury: false, starting_tribe: "pagong" },
        { id: "dirk-been",         placement: 12, jury: false, starting_tribe: "tagi" },
        { id: "ramona-gray",       placement: 13, jury: false, starting_tribe: "pagong" },
        { id: "stacey-stillman",   placement: 14, jury: false, starting_tribe: "tagi" },
        { id: "b-b-andersen",      placement: 15, jury: false, starting_tribe: "pagong" },
        { id: "sonja-christopher", placement: 16, jury: false, starting_tribe: "tagi" },
      ]
    },
    {
      number: 2, name: "The Australian Outback", year: 2001, color: "#7a9e7e", allstar: false,
      favourites: ["jerri-manthey", "colby-donaldson", "jeff-varner"],
      cast: [
        { id: "tina-wesson",        placement: 1,  jury: false, starting_tribe: "Ogakor" },
        { id: "colby-donaldson",    placement: 2,  jury: false, starting_tribe: "Ogakor"  },
        { id: "keith-famie",     placement: 3,  jury: true, starting_tribe: "Ogakor"  },
        { id: "elisabeth-filarski", placement: 4,  jury: true, starting_tribe: "Kucha"  },
        { id: "rodger-bingham",        placement: 5,  jury: true, starting_tribe: "Kucha"  },
        { id: "amber-brkich",     placement: 6,  jury: true, starting_tribe: "Ogakor"  },
        { id: "nick-brown",      placement: 7,  jury: true, starting_tribe: "Kucha"  },
        { id: "jerri-manthey",         placement: 8,  jury: true, starting_tribe: "Ogakor"  },
        { id: "alicia-calaway",       placement: 9,  jury: true, starting_tribe: "Kucha" },
        { id: "jeff-varner",        placement: 10, jury: false, starting_tribe: "Kucha" },
        { id: "michael-skupin",     placement: 11, jury: false, note: "medevac", starting_tribe: "Kucha" },
        { id: "kimmi-kappenberg",   placement: 12, jury: false, starting_tribe: "Kucha" },
        { id: "mitchell-olson",     placement: 13, jury: false, starting_tribe: "Ogakor" },
        { id: "maralyn-hershey",    placement: 14, jury: false, starting_tribe: "Ogakor" },
        { id: "kel-gleason",        placement: 15, jury: false, starting_tribe: "Ogakor" },
        { id: "debb-eaton",         placement: 16, jury: false, starting_tribe: "Kucha" },
      ]
    },
    {
      number: 3, name: "Africa", year: 2001, color: "#c4a35a", allstar: false,
      favourites: ["brandon-quinton", "linda-spencer", "silas-gaither"],
      cast: [
        { id: "ethan-zohn",         placement: 1,  jury: false, starting_tribe: "Boran"  },
        { id: "kim-johnson",        placement: 2,  jury: false, starting_tribe: "Boran"   },
        { id: "lex-van-den-berghe", placement: 3,  jury: true, starting_tribe: "Boran"   },
        { id: "tom-buchanan",       placement: 4,  jury: true, starting_tribe: "Boran"   },
        { id: "teresa-cooper",      placement: 5,  jury: true, starting_tribe: "Samburu"   },
        { id: "kim-powers",     placement: 6,  jury: true, starting_tribe: "Samburu"   },
        { id: "frank-garrison",    placement: 7,  jury: true, starting_tribe: "Samburu"   },
        { id: "brandon-quinton",         placement: 8,  jury: true, starting_tribe: "Samburu"  },
        { id: "kelly-goldsmith",    placement: 9,  jury: true, starting_tribe: "Boran"  },
        { id: "clarence-black",      placement: 10, jury: false, starting_tribe: "Boran"  },
        { id: "lindsey-richter",     placement: 11, jury: false, starting_tribe: "Samburu"  },
        { id: "silas-gaither",      placement: 12, jury: false, starting_tribe: "Samburu"  },
        { id: "linda-spencer",      placement: 13, jury: false, starting_tribe: "Samburu"  },
        { id: "carl-schmidt",       placement: 14, jury: false, starting_tribe: "Samburu"  },
        { id: "jessie-camacho",     placement: 15, jury: false, starting_tribe: "Boran"  },
        { id: "diane-ogden",        placement: 16, jury: false, starting_tribe: "Boran"  },
      ]
    },
    {
      number: 4, name: "Marquesas", year: 2002, color: "#8a7fa0", allstar: false,
      favourites: ["rob-mariano", "sean-rector", "kathy-vavrick-obrien"],
      cast: [
        { id: "vecepia-towery",       placement: 1,  jury: false },
        { id: "neleh-dennis",         placement: 2,  jury: false  },
        { id: "kathy-vavrick-obrien",      placement: 3,  jury: true  },
        { id: "paschal-english", placement: 4,  jury: true  },
        { id: "sean-rector",          placement: 5,  jury: true  },
        { id: "the-general",        placement: 6,  jury: true  },
        { id: "tammy-leitner",          placement: 7,  jury: true  },
        { id: "zoe-zanidakis",        placement: 8,  jury: true },
        { id: "john-carroll",         placement: 9,  jury: true },
        { id: "rob-mariano",          placement: 10, jury: false },
        { id: "gina-crews",         placement: 11, jury: false },
        { id: "gabriel-cade",           placement: 12, jury: false },
        { id: "sarah-jones",          placement: 13, jury: false },
        { id: "hunter-ellis",         placement: 14, jury: false },
        { id: "patricia-jackson",     placement: 15, jury: false },
        { id: "peter-harkey",         placement: 16, jury: false },
      ]
    },
    {
      number: 5, name: "Thailand", year: 2002, color: "#7a9eb8", allstar: false,
      favourites: ["shii-ann-huang", "ken-stafford", "ghandia-johnson"],
      cast: [
        { id: "brian-heidik",     placement: 1,  jury: false },
        { id: "clay-jordan",      placement: 2,  jury: false  },
        { id: "jan-gentry",       placement: 3,  jury: true  },
        { id: "helen-glover",     placement: 4,  jury: true  },
        { id: "ted-rogers",       placement: 5,  jury: true  },
        { id: "jake-billingsley",     placement: 6,  jury: true  },
        { id: "penny-ramsey", placement: 7,  jury: true  },
        { id: "ken-stafford",     placement: 8,  jury: true },
        { id: "erin-collins",     placement: 9,  jury: true },
        { id: "shii-ann-huang",   placement: 10,  jury: false },
        { id: "robb-zbacnik",     placement: 11, jury: false },
        { id: "stephanie-dill",   placement: 12, jury: false },
        { id: "ghandia-johnson",  placement: 13, jury: false },
        { id: "jed-hildebrand",   placement: 14, jury: false },
        { id: "tanya-vance",     placement: 15, jury: false },
        { id: "john-raymond",      placement: 16, jury: false },
      ]
    },
    {
      number: 6, name: "The Amazon", year: 2003, color: "#6b9e6b", allstar: false,
      favourites: ["rob-cesternino", "deena-bennett", "christy-smith"],
      cast: [
        { id: "jenna-morasca",        placement: 1,  jury: false },
        { id: "matthew-von-ertfelda", placement: 2,  jury: true  },
        { id: "rob-cesternino",        placement: 3,  jury: true  },
        { id: "butch-lockley",       placement: 4,  jury: true  },
        { id: "heidi-strobel",        placement: 5,  jury: true  },
        { id: "christy-smith",        placement: 6,  jury: true  },
        { id: "alex-bell",            placement: 7,  jury: true  },
        { id: "deena-bennett",        placement: 8,  jury: true  },
        { id: "dave-johnson",      placement: 9,  jury: true },
        { id: "roger-sexton",         placement: 10, jury: false },
        { id: "shawna-mitchell",         placement: 11, jury: false },
        { id: "jeanne-hebert",          placement: 12, jury: false },
        { id: "joanna-ward",        placement: 13, jury: false },
        { id: "daniel-lue",           placement: 14, jury: false },
        { id: "janet-koth",           placement: 15, jury: false },
        { id: "ryan-aiken",           placement: 16, jury: false },
      ]
    },
    {
      number: 7, name: "Pearl Islands", year: 2003, color: "#c07860", allstar: false,
      favourites: ["jon-dalton", "burton-roberts", "sandra-diaz-twine"],
      cast: [
        { id: "sandra-diaz-twine", placement: 1,  jury: false, starting_tribe: "Drake" },
        { id: "lillian-morris",    placement: 2,  jury: false, note: "voted out 3rd and returned", starting_tribe: "Morgan"  },
        { id: "jon-dalton",        placement: 3,  jury: true, starting_tribe: "Drake"  },
        { id: "darrah-johnson",    placement: 4,  jury: true, starting_tribe: "Morgan"  },
        { id: "burton-roberts",    placement: 5,  jury: true, note: "voted out 4th and returned", starting_tribe: "Drake"  },
        { id: "christa-hastie",    placement: 6,  jury: true, starting_tribe: "Drake"  },
        { id: "tijuana-bradley",    placement: 7,  jury: true, starting_tribe: "Morgan"  },
        { id: "rupert-boneham",   placement: 8,  jury: true, starting_tribe: "Drake" },
        { id: "ryan-opray",     placement: 9,  jury: true, starting_tribe: "Morgan" },
        { id: "andrew-savage",      placement: 10, jury: false, starting_tribe: "Morgan" },
        { id: "osten-taylor",        placement: 11, jury: false, note: "quit", starting_tribe: "Morgan" },
        { id: "shawn-cohen",       placement: 12, jury: false, starting_tribe: "Drake" },
        { id: "trish-dunn",  placement: 13, jury: false, starting_tribe: "Drake" },
        { id: "michelle-tesauro",        placement: 14, jury: false, starting_tribe: "Drake" },
        { id: "ryan-shoulders",      placement: 15, jury: false, starting_tribe: "Morgan" },
        { id: "nicole-delma",    placement: 16, jury: false, starting_tribe: "Morgan" },
      ]
    },
    {
      number: 8, name: "All-Stars", year: 2004, color: "#7c5fa8", allstar: true,
      favourites: ["shii-ann-huang", "kathy-vavrick-obrien", "jerri-manthey"],
      cast: [
        { id: "amber-brkich",         placement: 1,  jury: false },
        { id: "rob-mariano",          placement: 2,  jury: false  },
        { id: "jenna-lewis",          placement: 3,  jury: true  },
        { id: "rupert-boneham",       placement: 4,  jury: true  },
        { id: "tom-buchanan",       placement: 5,  jury: true  },
        { id: "shii-ann-huang",         placement: 6,  jury: true  },
        { id: "alicia-calaway",       placement: 7,  jury: true  },
        { id: "kathy-vavrick-obrien", placement: 8,  jury: true  },
        { id: "lex-van-den-berghe",   placement: 9,  jury: true  },
        { id: "jerri-manthey",        placement: 10, jury: false },
        { id: "ethan-zohn",      placement: 11, jury: false },
        { id: "colby-donaldson",           placement: 12, jury: false },
        { id: "susan-hawk",        placement: 13, jury: false, note: "quit"  },
        { id: "richard-hatch",           placement: 14, jury: false},
        { id: "rob-cesternino",        placement: 15, jury: false},
        { id: "jenna-morasca",       placement: 16, jury: false, note: "quit"  },
        { id: "rudy-boesch",          placement: 17, jury: false },
        { id: "tina-wesson",          placement: 18, jury: false },
      ]
    },
  {
      number: 9, name: "Vanuatu", year: 2004, color: "#8aaa80", allstar: false,
      favourites: ["eliza-orlins", "ami-cusack", "twila-tanner"],
      cast: [
        { id: "chris-daughtery",         placement: 1,  jury: false },
        { id: "twila-tanner",          placement: 2,  jury: false  },
        { id: "scout-cloud-lee",          placement: 3,  jury: true  },
        { id: "eliza-orlins",       placement: 4,  jury: true  },
        { id: "julie-berry",       placement: 5,  jury: true  },
        { id: "ami-cusack",         placement: 6,  jury: true  },
        { id: "leann-slaby",       placement: 7,  jury: true  },
        { id: "chad-crittenden", placement: 8,  jury: true  },
        { id: "lea-masters",   placement: 9,  jury: true  },
        { id: "rory-freeman",        placement: 10, jury: false },
        { id: "john-kenney",      placement: 11, jury: false },
        { id: "lisa-keiffer",           placement: 12, jury: false },
        { id: "travis-simpson",        placement: 13, jury: false },
        { id: "brady-finta",           placement: 14, jury: false},
        { id: "mia-galeotalanza",        placement: 15, jury: false},
        { id: "john-palyok",       placement: 16, jury: false },
        { id: "dolly-neely",          placement: 17, jury: false },
        { id: "brook-geraghty",          placement: 18, jury: false },
      ]
    },
    {
      number: 10, name: "Palau", year: 2005, color: "#5a9ab0", allstar: false,
      favourites: ["tom-westman", "caryn-groedel", "coby-archa"],
      cast: [
        { id: "tom-westman",        placement: 1,  jury: false, starting_tribe: "Koror" },
        { id: "katie-gallagher",    placement: 2,  jury: false, starting_tribe: "Koror" },
        { id: "ian-rosenberger",    placement: 3,  jury: true,  starting_tribe: "Koror" },
        { id: "jenn-lyon",          placement: 4,  jury: true,  starting_tribe: "Koror" },
        { id: "caryn-groedel",      placement: 5,  jury: true,  starting_tribe: "Koror" },
        { id: "gregg-carey",        placement: 6,  jury: true,  starting_tribe: "Koror" },
        { id: "stephenie-lagrossa", placement: 7,  jury: true,  starting_tribe: "Ulong" },
        { id: "janu-tornell",       placement: 8,  jury: true,  starting_tribe: "Koror", note: "quit" },
        { id: "coby-archa",         placement: 9,  jury: true,  starting_tribe: "Koror" },
        { id: "bobby-jon-drinkard", placement: 10, jury: false, starting_tribe: "Ulong" },
        { id: "ibrehem-rahman",      placement: 11, jury: false, starting_tribe: "Koror" },
        { id: "james-miller",     placement: 12, jury: false, starting_tribe: "Ulong" },
        { id: "angie-jakusz",       placement: 13, jury: false, starting_tribe: "Ulong" },
        { id: "willard-smith",       placement: 14, jury: false, starting_tribe: "Ulong" },
        { id: "kim-mullen",         placement: 15, jury: false, starting_tribe: "Ulong" },
        { id: "jeff-wilson",        placement: 16, jury: false, starting_tribe: "Ulong", note: "quit from injury" },
        { id: "ashlee-ashby",       placement: 17, jury: false, starting_tribe: "Ulong" },
        { id: "jolanda-jones",      placement: 18, jury: false, starting_tribe: "Ulong" },
        { id: "wanda-shirk",        placement: 19, jury: false, note: "not picked in tribe selection" },
        { id: "jonathan-libby",     placement: 20, jury: false, note: "not picked in tribe selection" },
  ]
},
    {
      number: 11, name: "Guatemala", year: 2005, color: "#9e8060", allstar: true,
      favourites: ["jamie-newton", "brian-corridan", "rafe-judkins"],
      cast: [
        { id: "danni-boatwright",  placement: 1,  jury: false, starting_tribe: "Yaxha" },
        { id: "stephenie-lagrossa",placement: 2,  jury: false, starting_tribe: "Nakum" },
        { id: "rafe-judkins",      placement: 3,  jury: true,  starting_tribe: "Nakum"},
        { id: "lydia-morales",     placement: 4,  jury: true,  starting_tribe: "Yaxha" },
        { id: "cindy-hall",        placement: 5,  jury: true,  starting_tribe: "Nakum" },
        { id: "judd-sergeant",     placement: 6,  jury: true,  starting_tribe: "Yaxha" },
        { id: "gary-hogeboom",     placement: 7,  jury: true,  starting_tribe: "Nakum" },
        { id: "jamie-newton",      placement: 8,  jury: true,  starting_tribe: "Nakum" },
        { id: "bobby-jon-drinkard",placement: 9,  jury: true, starting_tribe: "Yaxha" },
        { id: "brandon-bellinger", placement: 10, jury: false, starting_tribe: "Nakum" },
        { id: "amy-ohara",         placement: 11, jury: false, starting_tribe: "Yaxha" },
        { id: "brian-corridan",    placement: 12, jury: false, starting_tribe: "Yaxha" },
        { id: "margaret-bobonich", placement: 13, jury: false, starting_tribe: "Nakum" },
        { id: "blake-towsley",     placement: 14, jury: false, starting_tribe: "Yaxha" },
        { id: "brooke-struck",   placement: 15, jury: false, starting_tribe: "Yaxha" },
        { id: "brianna-varela",     placement: 16, jury: false, starting_tribe: "Nakum" },
        { id: "morgan-mcdevitt",    placement: 17, jury: false, starting_tribe: "Yaxha" },
        { id: "jim-lynch",         placement: 18, jury: false, starting_tribe: "Nakum" },
  ]
},

          {
      number: 12, name: "Panama", year: 2006, color: "#7a9070", allstar: false,
      favourites: ["cirie-fields", "shane-powers", "aras-baskauskas"],
      cast: [
        { id: "aras-baskauskas",    placement: 1,  jury: false, starting_tribe: "Viveros" },
        { id: "danielle-dilorenzo", placement: 2,  jury: false, starting_tribe: "Casaya" },
        { id: "terry-deitz",        placement: 3,  jury: true,  starting_tribe: "La Mina" },
        { id: "cirie-fields",       placement: 4,  jury: true,  starting_tribe: "Casaya" },
        { id: "shane-powers",       placement: 5,  jury: true,  starting_tribe: "Bayoneta" },
        { id: "courtney-marit",     placement: 6,  jury: true,  starting_tribe: "Casaya" },
        { id: "bruce-kanegai",      placement: 7,  jury: true,  starting_tribe: "Viveros", note: "medevac" },
        { id: "sally-schumann",     placement: 8,  jury: true,  starting_tribe: "Bayoneta" },
        { id: "austin-carty",       placement: 9,  jury: true,  starting_tribe: "La Mina" },
        { id: "nick-stanbury",      placement: 10, jury: false, starting_tribe: "La Mina" },
        { id: "dan-barry",          placement: 11, jury: false, starting_tribe: "La Mina" },
        { id: "bobby-mason",        placement: 12, jury: false, starting_tribe: "Bayoneta" },
        { id: "ruth-marie-milliman",        placement: 13, jury: false, starting_tribe: "Viveros" },
        { id: "misty-giles",      placement: 14, jury: false, starting_tribe: "Casaya" },
        { id: "melinda-hyder",        placement: 15, jury: false, starting_tribe: "Casaya" },
        { id: "tina-scheer",        placement: 16, jury: false, starting_tribe: "Bayoneta" },
  ]
},
    {
      number: 13, name: "Cook Islands", year: 2006, color: "#5a9ab8", allstar: false,
      favourites: [],
      cast: [
        { id: "yul-kwon",           placement: 1,  jury: false, starting_tribe: "Puka Puka" },
        { id: "ozzy-lusth",         placement: 2,  jury: false, starting_tribe: "Aitutaki" },
        { id: "becky-lee",          placement: 3,  jury: false, starting_tribe: "Puka Puka" },
        { id: "sundra-oakley",      placement: 4,  jury: true,  starting_tribe: "Manihiki" },
        { id: "adam-gentry",    placement: 5,  jury: true,  starting_tribe: "Rarotonga" },
        { id: "parvati-shallow",   placement: 6,  jury: true,  starting_tribe: "Rarotonga" },
        { id: "jonathan-penner",        placement: 7,  jury: true,  starting_tribe: "Rarotonga" },
        { id: "candice-woodcock",    placement: 8,  jury: true,  starting_tribe: "Rarotonga"},
        { id: "nate-gonzalez",      placement: 9,  jury: true,  starting_tribe: "Manihiki" },
        { id: "jenny-guzon-bae",    placement: 10, jury: true,  starting_tribe: "Puka Puka" },
        { id: "rebecca-borman",     placement: 11, jury: true, starting_tribe: "Aitutaki" },
        { id: "brad-virata",        placement: 12, jury: true, starting_tribe: "Puka Puka" },
        { id: "flicka-smith",       placement: 13, jury: false, starting_tribe: "Rarotonga" },
        { id: "cristina-coria",        placement: 14, jury: false, starting_tribe: "Puka Puka" },
        { id: "cao-boi-bui",     placement: 15, jury: false, starting_tribe: "Manihiki" },
        { id: "stephannie-favor",   placement: 16, jury: false, starting_tribe: "Aitutaki" },
        { id: "jp-calderon",   placement: 17, jury: false, starting_tribe: "Manihiki" },
        { id: "cecilia-mansilla",        placement: 18, jury: false, starting_tribe: "Aitutaki" },
        { id: "billy-garcia",       placement: 19, jury: false, starting_tribe: "Aitutaki" },
        { id: "sekou-bunch",        placement: 20, jury: false, starting_tribe: "Manihiki" },
  ]
},
        {
      number: 14, name: "Fiji", year: 2007, color: "#b89a6a", allstar: false,
      favourites: ["earl-cole", "dreamz-herd", "yau-man-chan"],
      cast: [
        { id: "earl-cole",          placement: 1,  jury: false, starting_tribe: "Ravu" },
        { id: "cassandra-franklin", placement: 2,  jury: false, starting_tribe: "Moto" },
        { id: "dreamz-herd",        placement: 3,  jury: false, starting_tribe: "Moto" },
        { id: "yau-man-chan",       placement: 4,  jury: true,  starting_tribe: "Ravu" },
        { id: "boo-bernis",         placement: 5,  jury: true,  starting_tribe: "Moto" },
        { id: "stacy-kimball",      placement: 6,  jury: true,  starting_tribe: "Moto" },
        { id: "alex-angarita",      placement: 7,  jury: true,  starting_tribe: "Moto" },
        { id: "mookie-lee",         placement: 8,  jury: true,  starting_tribe: "Ravu" },
        { id: "edgardo-rivera",     placement: 9,  jury: true,  starting_tribe: "Moto" },
        { id: "michelle-yi",        placement: 10, jury: true, starting_tribe: "Moto" },
        { id: "lisi-linares",       placement: 11, jury: true, starting_tribe: "Ravu" },
        { id: "rocky-reid",         placement: 12, jury: true, starting_tribe: "Ravu" },
        { id: "anthony-robinson",   placement: 13, jury: false, starting_tribe: "Ravu" },
        { id: "rita-verreos",       placement: 14, jury: false, starting_tribe: "Moto" },
        { id: "liliana-gomez",      placement: 15, jury: false, starting_tribe: "Moto" },
        { id: "gary-stritesky",     placement: 16, jury: false, starting_tribe: "Ravu", note: "medevac" },
        { id: "sylvia-kwan",        placement: 17, jury: false, starting_tribe: "Moto" },
        { id: "erica-durousseau",   placement: 18, jury: false, starting_tribe: "Ravu" },
        { id: "jessica-deben",      placement: 19, jury: false, starting_tribe: "Moto" },
      ]
    },

        {
      number: 15, name: "China", year: 2007, color: "#a64e3c", allstar: false,
      favourites: ["peih-gee-law", "todd-herzog", "amanda-kimmel"],
      cast: [
        { id: "todd-herzog",        placement: 1,  jury: false, starting_tribe: "Fei Long" },
        { id: "courtney-yates",     placement: 2,  jury: false, starting_tribe: "Fei Long" },
        { id: "amanda-kimmel",      placement: 3,  jury: false, starting_tribe: "Fei Long" },
        { id: "denise-martin",      placement: 4,  jury: true,  starting_tribe: "Zhan Hu" },
        { id: "peih-gee-law",       placement: 5,  jury: true,  starting_tribe: "Zhan Hu" },
        { id: "erik-huffman",       placement: 6,  jury: true,  starting_tribe: "Fei Long" },
        { id: "james-clement",        placement: 7,  jury: true,  starting_tribe: "Zhan Hu" },
        { id: "frosti-zernow", placement: 8, jury: true, starting_tribe: "Fei Long" },
        { id: "jean-robert-bellande",      placement: 9,  jury: true,  starting_tribe: "Zhan Hu" },
        { id: "jaime-dugan",   placement: 10, jury: true, starting_tribe: "Fei Long" },
        { id: "sherea-lloyd",       placement: 11, jury: false, starting_tribe: "Fei Long" },
        { id: "aaron-reisberger",        placement: 12, jury: false, starting_tribe: "Zhan Hu" },
        { id: "dave-cruser",     placement: 13, jury: false, starting_tribe: "Zhan Hu" },
        { id: "leslie-nease",       placement: 14, jury: false, starting_tribe: "Zhan Hu" },
        { id: "ashley-massaro", placement: 15, jury: false, starting_tribe: "Zhan Hu" },
        { id: "chicken-morris",       placement: 16, jury: false, starting_tribe: "Zhan Hu" },
      ]
    },
        {
      number: 16, name: "Micronesia", year: 2008, color: "#7b6aa8", allstar: true,
      favourites: ["cirie-fields","eliza-orlins","parvati-shallow"],
      cast: [
        // Favorites
        { id: "parvati-shallow", placement: 1,  jury: false, starting_tribe: "Malakal" },
        { id: "amanda-kimmel",   placement: 2,  jury: false, starting_tribe: "Malakal" },
        { id: "cirie-fields",    placement: 3,  jury: false, starting_tribe: "Malakal" },
        { id: "ozzy-lusth",      placement: 4,  jury: true,  starting_tribe: "Malakal" },
        { id: "james-clement",   placement: 5,  jury: true,  starting_tribe: "Malakal", note: "medevac" },
        { id: "jonathan-penner", placement: 6,  jury: true,  starting_tribe: "Malakal", note: "medevac" },
        { id: "yau-man-chan",    placement: 7,  jury: false, starting_tribe: "Malakal" },
        { id: "eliza-orlins",    placement: 10, jury: false, starting_tribe: "Malakal" },
        { id: "jon-dalton",          placement: 20, jury: false, starting_tribe: "Malakal", note: "quit" },
        { id: "ami-cusack",      placement: 14, jury: false, starting_tribe: "Malakal" },

        // Fans
        { id: "erik-reichenbach",  placement: 5,  jury: true,  starting_tribe: "Airai" },
        { id: "natalie-bolton",    placement: 4,  jury: true,  starting_tribe: "Airai" },
        { id: "alexis-jones",      placement: 6,  jury: true,  starting_tribe: "Airai" },
        { id: "jason-siska",       placement: 8,  jury: true,  starting_tribe: "Airai" },
        { id: "tracy-hughes-wolf", placement: 11, jury: false, starting_tribe: "Airai" },
        { id: "chet-welch",        placement: 15, jury: false, starting_tribe: "Airai", note: "quit" },
        { id: "kathy-sleckman",    placement: 16, jury: false, starting_tribe: "Airai", note: "quit" },
        { id: "mikey-bortone",     placement: 17, jury: false, starting_tribe: "Airai" },
        { id: "mary-sartain",      placement: 18, jury: false, starting_tribe: "Airai" },
        { id: "joel-anderson",     placement: 19, jury: false, starting_tribe: "Airai" },
      ]
    },
  ]
};
