// cast-data.js
// Add this before cast.html's script: <script src="cast-data.js"></script>
// Data covers S01–S08 only. Placement 1 = winner, highest = first boot.

window.CastData = {

  contestants: {
    // ── S1 Borneo ──────────────────────────────────────────────────────
    "richard-hatch":      { name: "Richard Hatch",                   bio: "The fabulous gay star of season 1 is revealed in season 8 to be a weirdo. Deeply disappointing. I hope not to be seeing him again." },
    "kelly-wiglesworth":  { name: "Kelly Wiglesworth",               bio: "" },
    "rudy-boesch":        { name: "Rudy Boesch",                     bio: "" },
    "susan-hawk":         { name: "Susan Hawk",                      bio: "The icon responsible for the game-shaping 'snakes and rats' speech." },
    "sean-kenniff":       { name: "Sean Kenniff",                    bio: "Voted alphabetically post-merge." },
    "colleen-haskell":    { name: "Colleen Haskell",                 bio: "" },
    "gervase-peterson":   { name: "Gervase Peterson",                bio: "" },
    "jenna-lewis":        { name: "Jenna Lewis",                     bio: "" },
    "greg-buis":          { name: "Greg Buis",                       bio: "" },
    "gretchen-cordy":     { name: "Gretchen Cordy",                  bio: "" },
    "joel-klug":          { name: "Joel Klug",                       bio: "" },
    "dirk-been":          { name: "Dirk Been",                       bio: "Brought a bible!" },
    "ramona-gray":        { name: "Ramona Gray",                     bio: "" },
    "stacey-stillman":    { name: "Stacey Stillman",                 bio: "" },
    "b-b-andersen":       { name: "B.B. Andersen",                   bio: "Fervently worked on building a shelter and then seemingly threw in the towel immediately!" },
    "sonja-christopher":  { name: "Sonja Christopher",               bio: "The first every person to be voted out of Survivor. Poor Sonja." },

    // ── S2 The Australian Outback ───────────────────────────────────────
    "tina-wesson":        { name: "Tina Wesson",                     bio: "" },
    "colby-donaldson":    { name: "Colby Donaldson",                 bio: "" },
    "amber-brkich":       { name: "Amber Brkich",                    bio: "Completely anonymous in the edit of Australian Outback, but somehow is brought back for All-Stars and ekes out a win based on her relationship with a certain Boston Rob." },
    "jerri-manthey":      { name: "Jerri Manthey",                   bio: "The first 'villain'. Love her. And I love how she's just as annoying on her second go!" },
    "elisabeth-filarski": { name: "Elisabeth Filarski",              bio: "" },
    "rodger-bingham":     { name: "Rodger Bingham",                  bio: "" },
    "alicia-calaway":     { name: "Alicia Calaway",                  bio: "" },
    "keith-famie":        { name: "Keith Famie",                     bio: "" },
    "nick-brown":         { name: "Nick Brown",                      bio: "" },
    "jeff-varner":        { name: "Jeff Varner",                     bio: "" },
    "michael-skupin":     { name: "Michael Skupin",                  bio: "" },
    "kimmi-kappenberg":   { name: "Kimmi Kappenberg",                bio: "Most Australian Outback drama in Kucha stemmed from the fact that she is a vegetarian. Woke messy queen!" },
    "mitchell-olson":     { name: "Mitchell Olson",                  bio: "" },
    "maralyn-hershey":    { name: "Maralyn Hershey",                 bio: "AKA Mad Dog!" },
    "kel-gleason":        { name: "Kel Gleason",                     bio: "Accused of smuggling beef jerky into the show and keeping it for himself. That was... not true, right?" },
    "debb-eaton":         { name: "Debb Eaton",                      bio: "" },

    // ── S3 Africa ──────────────────────────────────────────────────────
    "ethan-zohn":         { name: "Ethan Zohn",                      bio: "" },
    "kim-johnson":        { name: "Kim Johnson",                     bio: "" },
    "lex-van-den-berghe": { name: "Lex van den Berghe",              bio: "" },
    "tom-buchanan":       { name: "Tom Buchanan",                    bio: "" },
    "teresa-cooper":      { name: "Teresa Cooper",                   bio: "" },
    "frank-garrison":     { name: "Frank Garrison",                  bio: "" },
    "brandon-quinton":    { name: "Brandon Quinton",                 bio: "" },
    "kim-powers":         { name: "Kim Powers",                      bio: "" },
    "kelly-goldsmith":    { name: "Kelly Goldsmith",                 bio: "" },
    "linda-spencer":      { name: "Linda Spencer",                   bio: "" },
    "clarence-black":     { name: "Clarence Black",                  bio: "" },
    "silas-gaither":      { name: "Silas Gaither",                   bio: "" },
    "carl-schmidt":       { name: "Carl Schmidt",                    bio: "" },
    "jessie-camacho":     { name: "Jessie Camacho",                  bio: "" },
    "diane-ogden":        { name: "Diane Ogden",                     bio: "" },

    // ── S4 Marquesas ──────────────────────────────────────────────────
    "vecepia-towery":       { name: "Vecepia Towery",                bio: "" },
    "neleh-dennis":         { name: "Neleh Dennis",                  bio: "" },
    "paschal-english":      { name: "Paschal English",               bio: "" },
    "kathy-vavrick-obrien": { name: "Kathy Vavrick-O'Brien",        bio: "" },
    "sean-rector":          { name: "Sean Rector",                   bio: "" },
    "rob-mariano":          { name: "Rob Mariano",                   bio: "" },
    "tammy-leitner":        { name: "Tammy Leitner",                 bio: "" },
    "the-general":          { name: "The General (Robert DeCanio)", bio: "" },
    "zoe-zanidakis":        { name: "Zoe Zanidakis",                 bio: "" },
    "john-carroll":         { name: "John Carroll",                  bio: "" },
    "gabriel-cade":         { name: "Gabriel Cade",                  bio: "" },
    "gina-crews":           { name: "Gina Crews",                    bio: "" },
    "sarah-jones":          { name: "Sarah Jones",                   bio: "" },
    "hunter-ellis":         { name: "Hunter Ellis",                  bio: "" },
    "patricia-jackson":     { name: "Patricia Jackson",              bio: "" },
    "peter-harkey":         { name: "Peter Harkey",                  bio: "" },

    // ── S5 Thailand ───────────────────────────────────────────────────
    "brian-heidik":       { name: "Brian Heidik",                    bio: "" },
    "clay-jordan":        { name: "Clay Jordan",                     bio: "" },
    "jan-gentry":         { name: "Jan Gentry",                      bio: "" },
    "helen-glover":       { name: "Helen Glover",                    bio: "" },
    "ted-rogers":         { name: "Ted Rogers",                      bio: "" },
    "ken-stafford":       { name: "Ken Stafford",                    bio: "" },
    "jake-billingsley":   { name: "Jake Billingsley",                bio: "" },
    "penny-ramsey":       { name: "Penny Ramsey",                    bio: "" },
    "shii-ann-huang":     { name: "Shii Ann Huang",                  bio: "" },
    "robb-zbacnik":       { name: "Robb Zbacnik",                    bio: "" },
    "stephanie-dill":     { name: "Stephanie Dill",                  bio: "" },
    "ghandia-johnson":    { name: "Ghandia Johnson",                 bio: "" },
    "jed-hildebrand":     { name: "Jed Hildebrand",                  bio: "" },
    "john-raymond":       { name: "John Raymond",                    bio: "" },
    "tanya-vance":        { name: "Tanya Vance",                     bio: "" },

    // ── S6 The Amazon ─────────────────────────────────────────────────
    "jenna-morasca":        { name: "Jenna Morasca",                 bio: "" },
    "matthew-von-ertfelda": { name: "Matthew von Ertfelda",         bio: "" },
    "rob-cesternino":       { name: "Rob Cesternino",                bio: "" },
    "butch-lockley":        { name: "Butch Lockley",                 bio: "" },
    "heidi-strobel":        { name: "Heidi Strobel",                 bio: "" },
    "christy-smith":        { name: "Christy Smith",                 bio: "" },
    "alex-bell":            { name: "Alex Bell",                     bio: "" },
    "deena-bennett":        { name: "Deena Bennett",                 bio: "" },
    "shawna-mitchell":      { name: "Shawna Mitchell",               bio: "" },
    "dave-johnson":         { name: "Dave Johnson",                  bio: "" },
    "roger-sexton":         { name: "Roger Sexton",                  bio: "" },
    "joanna-ward":          { name: "Joanna Ward",                   bio: "" },
    "jeanne-hebert":        { name: "Jeanne Hebert",                 bio: "" },
    "ryan-scott":           { name: "Ryan Scott",                    bio: "" },
    "daniel-lue":           { name: "Daniel Lue",                    bio: "" },
    "ryan-aiken":           { name: "Ryan Aiken",                    bio: "" },

    // ── S7 Pearl Islands ──────────────────────────────────────────────
    "sandra-diaz-twine":  { name: "Sandra Diaz-Twine",               bio: "" },
    "lillian-morris":     { name: "Lillian Morris",                  bio: "" },
    "jon-dalton":         { name: "Jon Dalton",                      bio: "" },
    "darrah-johnson":     { name: "Darrah Johnson",                  bio: "" },
    "burton-roberts":     { name: "Burton Roberts",                  bio: "" },
    "christa-hastie":     { name: "Christa Hastie",                  bio: "" },
    "rupert-boneham":     { name: "Rupert Boneham",                  bio: "" },
    "tijuana-bradley":    { name: "Tijuana Bradley",                 bio: "" },
    "andrew-savage":      { name: "Andrew Savage",                   bio: "" },
    "osten-taylor":       { name: "Osten Taylor",                    bio: "" },
    "trish-dunn":         { name: "Trish Dunn",                      bio: "" },
    "shawn-cohen":        { name: "Shawn Cohen",                     bio: "" },
    "michelle-tesauro":   { name: "Michelle Tesauro",                bio: "" },
    "ryan-opray":         { name: "Ryan Opray",                      bio: "" },
    "nicole-delma":       { name: "Nicole Delma",                    bio: "" },
    "ryan-shoulders":     { name: "Ryan Shoulders",                  bio: "" },

    // ── S8 All-Stars ─────────────────────────────────────────────────
    // (all contestants already defined above — no new entries needed)
  },

  seasons: [
    {
      number: 1, name: "Borneo", year: 2000, color: "#c8845a", allstar: false,
      favourites: ["richard-hatch", "susan-hawk", "greg-buis"],
      cast: [
        { id: "richard-hatch",     placement: 1,  jury: false, starting_tribe: "tagi" },
        { id: "kelly-wiglesworth", placement: 2,  jury: false, starting_tribe: "tagi" },
        { id: "rudy-boesch",       placement: 3,  jury: true, starting_tribe: "tagi"  },
        { id: "susan-hawk",        placement: 4,  jury: true, starting_tribe: "tagi"  },
        { id: "sean-kenniff",      placement: 5,  jury: true, starting_tribe: "tagi"  },
        { id: "colleen-haskell",   placement: 6,  jury: true, starting_tribe: "pagong"  },
        { id: "gervase-peterson",  placement: 7,  jury: true, starting_tribe: "pagong"  },
        { id: "jenna-lewis",       placement: 8,  jury: true, starting_tribe: "pagong" },
        { id: "greg-buis",         placement: 9,  jury: false, starting_tribe: "pagong" },
        { id: "gretchen-cordy",    placement: 10, jury: false, starting_tribe: "pagong" },
        { id: "joel-klug",         placement: 11, jury: false, starting_tribe: "pagong" },
        { id: "dirk-been",         placement: 12, jury: false, starting_tribe: "tagi" },
        { id: "ramona-gray",       placement: 13, jury: false, starting_tribe: "pagong" },
        { id: "stacey-stillman",   placement: 14, jury: false, starting_tribe: "tagi" },
        { id: "b-b-andersen",      placement: 15, jury: false, starting_tribe: "pagong" },
        { id: "sonja-christopher", placement: 16, jury: false, starting_tribe: "tagi" },
      ]
    },
    {
      number: 2, name: "The Australian Outback", year: 2001, color: "#7a9e7e", allstar: false,
      favourites: ["jerri-manthey", "colby-donaldson", "jeff-varner"],
      cast: [
        { id: "tina-wesson",        placement: 1,  jury: false, starting_tribe: "Ogakor" },
        { id: "colby-donaldson",    placement: 2,  jury: false, starting_tribe: "Ogakor"  },
        { id: "keith-famie",     placement: 3,  jury: true, starting_tribe: "Ogakor"  },
        { id: "elisabeth-filarski", placement: 4,  jury: true, starting_tribe: "Kucha"  },
        { id: "rodger-bingham",        placement: 5,  jury: true, starting_tribe: "Kucha"  },
        { id: "amber-brkich",     placement: 6,  jury: true, starting_tribe: "Ogakor"  },
        { id: "nick-brown",      placement: 7,  jury: true, starting_tribe: "Kucha"  },
        { id: "jerri-manthey",         placement: 8,  jury: true, starting_tribe: "Ogakor"  },
        { id: "alicia-calaway",       placement: 9,  jury: false, starting_tribe: "Kucha" },
        { id: "jeff-varner",        placement: 10, jury: false, starting_tribe: "Kucha" },
        { id: "michael-skupin",     placement: 11, jury: false, note: "medevac", starting_tribe: "Kucha" },
        { id: "kimmi-kappenberg",   placement: 12, jury: false, starting_tribe: "Kucha" },
        { id: "mitchell-olson",     placement: 13, jury: false, starting_tribe: "Ogakor" },
        { id: "maralyn-hershey",    placement: 14, jury: false, starting_tribe: "Ogakor" },
        { id: "kel-gleason",        placement: 15, jury: false, starting_tribe: "Ogakor" },
        { id: "debb-eaton",         placement: 16, jury: false, starting_tribe: "Kucha" },
      ]
    },
    {
      number: 3, name: "Africa", year: 2001, color: "#c4a35a", allstar: false,
      favourites: ["brandon-quinton", "linda-spencer", "silas-gaither"],
      cast: [
        { id: "ethan-zohn",         placement: 1,  jury: false },
        { id: "kim-johnson",        placement: 2,  jury: true  },
        { id: "lex-van-den-berghe", placement: 3,  jury: true  },
        { id: "tom-buchanan",       placement: 4,  jury: true  },
        { id: "teresa-cooper",      placement: 5,  jury: true  },
        { id: "frank-garrison",     placement: 6,  jury: true  },
        { id: "brandon-quinton",    placement: 7,  jury: true  },
        { id: "kim-powers",         placement: 8,  jury: false },
        { id: "kelly-goldsmith",    placement: 9,  jury: false },
        { id: "linda-spencer",      placement: 10, jury: false },
        { id: "clarence-black",     placement: 11, jury: false },
        { id: "silas-gaither",      placement: 12, jury: false },
        { id: "carl-schmidt",       placement: 13, jury: false },
        { id: "jessie-camacho",     placement: 14, jury: false },
        { id: "diane-ogden",        placement: 15, jury: false },
      ]
    },
    {
      number: 4, name: "Marquesas", year: 2002, color: "#8a7fa0", allstar: false,
      favourites: ["rob-mariano", "sean-rector", "kathy-vavrick-obrien"],
      cast: [
        { id: "vecepia-towery",       placement: 1,  jury: false },
        { id: "neleh-dennis",         placement: 2,  jury: true  },
        { id: "paschal-english",      placement: 3,  jury: true  },
        { id: "kathy-vavrick-obrien", placement: 4,  jury: true  },
        { id: "sean-rector",          placement: 5,  jury: true  },
        { id: "tammy-leitner",        placement: 6,  jury: true  },
        { id: "the-general",          placement: 7,  jury: true  },
        { id: "zoe-zanidakis",        placement: 8,  jury: false },
        { id: "john-carroll",         placement: 9,  jury: false },
        { id: "rob-mariano",          placement: 10, jury: false },
        { id: "gabriel-cade",         placement: 11, jury: false },
        { id: "gina-crews",           placement: 12, jury: false },
        { id: "sarah-jones",          placement: 13, jury: false },
        { id: "hunter-ellis",         placement: 14, jury: false },
        { id: "patricia-jackson",     placement: 15, jury: false },
        { id: "peter-harkey",         placement: 16, jury: false },
      ]
    },
    {
      number: 5, name: "Thailand", year: 2002, color: "#7a9eb8", allstar: false,
      favourites: ["shii-ann-huang", "ken-stafford", "ghandia-johnson"],
      cast: [
        { id: "brian-heidik",     placement: 1,  jury: false },
        { id: "clay-jordan",      placement: 2,  jury: true  },
        { id: "jan-gentry",       placement: 3,  jury: true  },
        { id: "helen-glover",     placement: 4,  jury: true  },
        { id: "ted-rogers",       placement: 5,  jury: true  },
        { id: "ken-stafford",     placement: 6,  jury: true  },
        { id: "jake-billingsley", placement: 7,  jury: true  },
        { id: "penny-ramsey",     placement: 8,  jury: false },
        { id: "shii-ann-huang",   placement: 9,  jury: false },
        { id: "robb-zbacnik",     placement: 10, jury: false },
        { id: "stephanie-dill",   placement: 11, jury: false },
        { id: "ghandia-johnson",  placement: 12, jury: false },
        { id: "jed-hildebrand",   placement: 13, jury: false },
        { id: "john-raymond",     placement: 14, jury: false },
        { id: "tanya-vance",      placement: 15, jury: false },
      ]
    },
    {
      number: 6, name: "The Amazon", year: 2003, color: "#6b9e6b", allstar: false,
      favourites: ["rob-cesternino", "deena-bennett", "christy-smith"],
      cast: [
        { id: "jenna-morasca",        placement: 1,  jury: false },
        { id: "matthew-von-ertfelda", placement: 2,  jury: true  },
        { id: "butch-lockley",        placement: 3,  jury: true  },
        { id: "rob-cesternino",       placement: 4,  jury: true  },
        { id: "heidi-strobel",        placement: 5,  jury: true  },
        { id: "christy-smith",        placement: 6,  jury: true  },
        { id: "alex-bell",            placement: 7,  jury: true  },
        { id: "deena-bennett",        placement: 8,  jury: true  },
        { id: "shawna-mitchell",      placement: 9,  jury: false },
        { id: "dave-johnson",         placement: 10, jury: false },
        { id: "roger-sexton",         placement: 11, jury: false },
        { id: "joanna-ward",          placement: 12, jury: false },
        { id: "jeanne-hebert",        placement: 13, jury: false },
        { id: "ryan-scott",           placement: 14, jury: false },
        { id: "daniel-lue",           placement: 15, jury: false },
        { id: "ryan-aiken",           placement: 16, jury: false },
      ]
    },
    {
      number: 7, name: "Pearl Islands", year: 2003, color: "#c07860", allstar: false,
      favourites: ["jon-dalton", "burton-roberts", "sandra-diaz-twine"],
      cast: [
        { id: "sandra-diaz-twine", placement: 1,  jury: false },
        { id: "lillian-morris",    placement: 2,  jury: true  },
        { id: "jon-dalton",        placement: 3,  jury: true  },
        { id: "darrah-johnson",    placement: 4,  jury: true  },
        { id: "burton-roberts",    placement: 5,  jury: true  },
        { id: "christa-hastie",    placement: 6,  jury: true  },
        { id: "rupert-boneham",    placement: 7,  jury: true  },
        { id: "tijuana-bradley",   placement: 8,  jury: false },
        { id: "andrew-savage",     placement: 9,  jury: false },
        { id: "osten-taylor",      placement: 10, jury: false, note: "quit" },
        { id: "trish-dunn",        placement: 11, jury: false },
        { id: "shawn-cohen",       placement: 12, jury: false },
        { id: "michelle-tesauro",  placement: 13, jury: false },
        { id: "ryan-opray",        placement: 14, jury: false },
        { id: "nicole-delma",      placement: 15, jury: false },
        { id: "ryan-shoulders",    placement: 16, jury: false },
      ]
    },
    {
      number: 8, name: "All-Stars", year: 2004, color: "#7c5fa8", allstar: true,
      favourites: ["shii-ann-huang", "kathy-vavrick-obrien", "jerri-manthey"],
      cast: [
        { id: "amber-brkich",         placement: 1,  jury: false },
        { id: "rob-mariano",          placement: 2,  jury: true  },
        { id: "jenna-lewis",          placement: 3,  jury: true  },
        { id: "rupert-boneham",       placement: 4,  jury: true  },
        { id: "alicia-calaway",       placement: 5,  jury: true  },
        { id: "tom-buchanan",         placement: 6,  jury: true  },
        { id: "shii-ann-huang",       placement: 7,  jury: true  },
        { id: "kathy-vavrick-obrien", placement: 8,  jury: true  },
        { id: "lex-van-den-berghe",   placement: 9,  jury: true  },
        { id: "jerri-manthey",        placement: 10, jury: false },
        { id: "colby-donaldson",      placement: 11, jury: false },
        { id: "ethan-zohn",           placement: 12, jury: false },
        { id: "richard-hatch",        placement: 13, jury: false },
        { id: "susan-hawk",           placement: 14, jury: false, note: "quit" },
        { id: "jenna-morasca",        placement: 15, jury: false, note: "quit" },
        { id: "rob-cesternino",       placement: 16, jury: false },
        { id: "rudy-boesch",          placement: 17, jury: false },
        { id: "tina-wesson",          placement: 18, jury: false },
      ]
    },
  ]
};
